import { ILang } from "./interface";
export const enUS: ILang = {
  algorithm: "Algorithm",
  codeRule: "Code rule",
  confirm: "Confirm",
  content: "Content",
  contentRequired: "Content is required",
  dataIsRequired: "Data is required",
  initialValue: "Initial value",
  invalidInput: "Invalid input",
  lblRemark: "Remark",
  lblRequired: "Required",
  length: "length",
  maximumNotBeExceed: "The maximum value cannot exceed {n}",
  maxStringLength: "Maximum characters cannot exceed {n}",
  minStringLength: "最短不能少于{n}个字符",
  neverReset: "Never reset",
  numberDigits: "{n} digits",
  paddingCharactor: "Padding charactor",
  parameterName: "Parameter name",
  parameterNameRequired: "Parameter name required",
  pleaseEnter: "Please enter",
  pleaseSelect: "Please select",
  resetEveryDay: "Reset every day",
  resetEveryMonth: "Reset every month",
  resetEveryYear: "Reset every year",
  resetPeriod: "Reset duration",
  scope: "Scope",
  sequence_autoIncrement: "Auto increment",
  sequence_checksum: "Checksum",
  sequence_dayOfMonth: "Day of month",
  sequence_dayOfWeek: "Day of week",
  sequence_dayOfYear: "Day of year",
  sequence_literal: "Literal",
  sequence_month: "Month",
  sequence_parameterValue: "Parameter value",
  sequence_userInput: "Text",
  sequence_weekOfYear: "Week of year",
  sequence_year: "Year",
  symbolColon: ": ",
  type: "Type",
};
